---
- name: Create a MySQL database for Drupal.
  mysql_db: "db={{ domain }} state=present login_unix_socket=/var/run/mysqld/mysqld.sock"

- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ domain }}"
    password: "1234"
    priv: "{{ domain }}.*:ALL"
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock