# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server01" do |srv|
    srv.vm.box = "geerlingguy/ubuntu1804"
    srv.vm.hostname = "drupal.lab"
    srv.vm.network "private_network", ip: "192.168.57.12"
    srv.vm.network "forwarded_port", guest: 80, host: 8080
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end
end